theme: minimal

title: "Kuda Innocent's Portfolio"
description: "Professional Portfolio - Masters in Information Systems"
url: "https://KudaInnocent.github.io/Inoocent-kuda-portfolio"
author: "Kuda Innocent"
email: "innocent.tsenzete@gmail.com"
